src/AppBundle/Entity/Event.php
<?php

namespace AppBundle\Entity;

use DateInterval;
use Doctrine\ORM\Mapping as ORM;

/**
 * Event
 *
 * @ORM\Table(name="event")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\EventRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Event
{
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->startDatetime = new \DateTime('now');
        $this->endDatetime = new \DateTime('now');
    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="startDatetime", type="datetime")
     */
    private $startDatetime;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="endDatetime", type="datetime")
     */
    private $endDatetime;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Action", inversedBy="periods", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $action;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set startDatetime
     *
     * @param \DateTime $startDatetime
     *
     * @return Event
     */
    public function setStartDatetime($startDatetime)
    {
        $this->startDatetime = $startDatetime;

        return $this;
    }

    /**
     * Get startDatetime
     *
     * @return \DateTime
     */
    public function getStartDatetime()
    {
        return $this->startDatetime;
    }

    /**
     * Set endDatetime
     *
     * @param \DateTime $endDatetime
     *
     * @return Event
     */
    public function setEndDatetime($endDatetime)
    {
        $this->endDatetime = $endDatetime;

        return $this;
    }

    /**
     * Get endDatetime
     *
     * @return \DateTime
     */
    public function getEndDatetime()
    {
        return $this->endDatetime;
    }

    /**
     * Set action
     *
     * @param \AppBundle\Entity\Action $action
     * @return Event
     */
    public function setAction(Action $action)
    {
        $this->action = $action;

        return $this;
    }

    /**
     * Get action
     *
     * @return \AppBundle\Entity\Action
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Get status
     *
     */
    public function getStatus()
    {
        $now = new \DateTime('now');

        if ($now > $this->endDatetime) {
            return 'CompletedAction';
        } elseif ($now >= $this->startDatetime && $now <= $this->endDatetime) {
            return 'ActiveAction';
        } elseif ($now < $this->startDatetime) {
            return 'PotentialAction';
        }
    }

    /**
     * Get a label for the DateInterval
     *
     */
    public function getIntervalLabel(){
        $start = $this->startDatetime->format('U');
        $end = $this->endDatetime->format('U');

        $startDay = date('d',$start);
        $startMonth = date('F',$start);
        $startYear = date('Y',$start);

        $endDay = date('d',$end);
        $endMonth = date('F',$end);
        $endYear = date('Y',$end);

        //For different years
        if($startYear < $endYear){
            $label = "Du ".$startDay."/".$startMonth."/".$startYear." au ".$endDay."/".$endMonth."/".$endYear;
        }elseif($startMonth < $endMonth){
            // For different months years
            $label = "Du ".$startDay." ".$startMonth." au ".$endDay." ".$endMonth." ".$endYear;
        }elseif($startDay < $endDay){
            // For different days
            $label = "Du ".$startDay." au ".$endDay." ".$endMonth." ".$endYear;
        }else{
            $label = "Le ".$startDay." ".$startMonth." ".$startYear;
        }

        $english = array('January','February','March','April','May','June','July','August','September','October','November','December');
        $french = array('Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre');

        $label = str_replace($english, $french, $label);

        return $label;
    }

    /**
     * Get duration
     *
     */
    public function getDuration(){
        $diff  = $this->endDatetime->diff($this->startDatetime);

        return $diff;
    }

    /**
     * Get duration label
     *
     */
    public function getDurationLabel(){
        $diff  = $this->getDuration();
        $duration = $this->format_duration($diff);

        return $duration;
    }

    /**
     * Format an interval to show all existing components.
     * If the interval doesn't have a time component (years, months, etc)
     * That component won't be displayed.
     *
     * @param DateInterval $interval The interval
     *
     * @return string Formatted interval string.
     */
    function format_duration(DateInterval $interval) {
        $result = "";

        // Years
        if ($interval->y) {
            if($interval->y == 1){
                $result .= $interval->format("%y an ");
            }else{
                $result .= $interval->format("%y ans ");
            }
        }

        // Months
        if ($interval->m) {
            $result .= $interval->format("%m mois ");
        }

        // Days
        if ($interval->d) {

            if($interval->d == 1){
                $result .= $interval->format("%d jour ");
            }else{
                $result .= $interval->format("%d jours ");
            }
        }

        // Hours
        if ($interval->h) {
            $result .= $interval->format("%hh");
        }

        // Minutes
        if ($interval->i) {
            $result .= $interval->format("%im ");
        }

        return $result;
    }



}

src/AppBundle/Controller/ActionController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Crop;
use AppBundle\Entity\CropCycle;
use AppBundle\Entity\InterventionCategory;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use AppBundle\Entity\Action;
use AppBundle\Form\ActionType;
use Symfony\Component\Security\Acl\Domain\ObjectIdentity;
use Symfony\Component\Security\Acl\Domain\UserSecurityIdentity;
use Symfony\Component\Security\Acl\Permission\MaskBuilder;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * Action controller.
 *
 * @Security("has_role('ROLE_USER')")
 * @Route("/")
 */
class ActionController extends Controller
{
    /**
     * Lists all Action entities for a specific crop cycle
     *
     * @Route("/cropcycle/{id}/action", name="action_index")
     * @Method("GET")
     */
    public function indexAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $cropCycle = $this->getDoctrine()->getManager()->getRepository('AppBundle:CropCycle')->find($id);

        // Check for edit access
        $authorizationChecker = $this->get('security.authorization_checker');
        if (false === $authorizationChecker->isGranted('VIEW', $cropCycle)) {
            throw new AccessDeniedException();
        }

        // Find actions for current cropCycle
        $actions = $em->getRepository('AppBundle:Action')->findByCropCycle($id);

        return $this->render('@App/action/index.html.twig', array(
            'actions' => $actions,
            'cropCycle' => $cropCycle,
        ));
    }

    /**
     * Lists all Action entities for a specific intervention category
     *
     * @Route("/action/category/{id}", name="action_by_category")
     * @Method("GET")
     */
    public function listByCategoryAction(Request $request, InterventionCategory $id)
    {
        $em = $this->getDoctrine()->getManager();

        $category = $this->getDoctrine()->getManager()->getRepository('AppBundle:InterventionCategory')->find($id);

        // Find actions for current intervention category
        $actions = $em->getRepository('AppBundle:Action')->findByInterventionCategory($id);

        return $this->render('@App/action/listByCategory.html.twig', array(
            'actions' => $actions,
            'category' => $category,
        ));
    }

    /**
     * Lists all Action entities for a specific crop
     *
     * @Route("/action/crop/{id}", name="action_by_crop")
     * @Method("GET")
     */
    public function listByCropAction(Request $request, Crop $id)
    {
        $em = $this->getDoctrine()->getManager();

        $crop = $this->getDoctrine()->getManager()->getRepository('AppBundle:Crop')->find($id);

        // Find actions for current intervention category
        $actions = $em->getRepository('AppBundle:Action')->findByCrop($id);

        return $this->render('@App/action/listByCrop.html.twig', array(
            'actions' => $actions,
            'crop' => $crop,
        ));
    }

    /**
     * Creates a new Action entity.
     *
     * @Route("/cropcycle/{id}/action/new", name="action_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request, $id)
    {
        $action = new Action();

        // Get Entity Manager
        $em = $this->getDoctrine()->getManager();

        // Get current cropCycle
        $cropCycle = $em->getRepository('AppBundle:CropCycle')->find($id);

        // Check for edit access
        $authorizationChecker = $this->get('security.authorization_checker');
        if (false === $authorizationChecker->isGranted('EDIT', $cropCycle)) {
            throw new AccessDeniedException();
        }

        // Link this action to current crop cycle
        $cropCycle->addAction($action); // Which also setCropcycle($this) on $action

        $form = $this->createForm(ActionType::class, $action);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($action);
            $em->flush();

            // Call ACL service
            $aclProvider = $this->get('security.acl.provider');

            // Create the ACL for current Action $action
            $objectIdentity = ObjectIdentity::fromDomainObject($action);
            $acl = $aclProvider->createAcl($objectIdentity);

            // Retrieve the security identity of the current user
            $securityIdentity = UserSecurityIdentity::fromAccount($this->getUser());

            // Create Access Mask
            $builder = new MaskBuilder();
            $builder
                ->add('view')
                ->add('edit')
                ->add('delete');
            $mask = $builder->get();

            // Insert Object Access Entry
            $acl->insertObjectAce($securityIdentity, $mask);

            // Update ACL
            $aclProvider->updateAcl($acl);

            return $this->redirectToRoute('cropcycle_show', array('id' => $action->getCropCycle()->getId()));
        }

        return $this->render('@App/action/new.html.twig', array(
            'cropCycle' => $cropCycle,
            'action' => $action,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Action entity.
     *
     * @Security("is_granted('VIEW', action) or is_granted('ROLE_ADMIN')")
     * @Route("/action/{id}", name="action_show")
     * @Method("GET")
     */
    public function showAction(Action $action)
    {
        $deleteForm = $this->createDeleteForm($action);

        return $this->render('@App/action/show.html.twig', array(
            'action' => $action,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Action entity.
     *
     * @Security("is_granted('EDIT', action) or is_granted('ROLE_ADMIN')")
     * @Route("/action/{id}/edit", name="action_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Action $action)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $deleteForm = $this->createDeleteForm($action);

        $originalPeriods = new ArrayCollection();

        // Create an ArrayCollection of the current Action->periods objects in the database
        foreach ($action->getPeriods() as $period) {
            $originalPeriods->add($period);
        }

        $editForm = $this->createForm('AppBundle\Form\ActionEditType', $action);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {

            // remove the relationship between the Period and the Action
            foreach ($originalPeriods as $period) {
                if (false === $action->getPeriods()->contains($period)) {
                    $em->remove($period);
                }
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($action);
            $em->flush();

            return $this->redirectToRoute('action_show', array('id' => $action->getId()));
        }

        return $this->render('@App/action/edit.html.twig', array(
            'action' => $action,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a Action entity.
     *
     *
     * @Route("/action/delete/{id}", name="action_delete")
     * @Security("is_granted('DELETE', action) or is_granted('ROLE_ADMIN')")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Action $action)
    {
        $form = $this->createDeleteForm($action);
        $form->handleRequest($request);

        $id = $action->getCropCycle()->getId();

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($action);
            $em->flush();
        }

        return $this->redirectToRoute('cropcycle_show', array('id' => $id));
    }

    /**
     * Creates a form to delete a Action entity.
     *
     * @param Action $action The Action entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Action $action)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('action_delete', array('id' => $action->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/AppBundle/Resources/views/action/edit.html.twig
{% extends 'base.html.twig' %}

{% block plugin_stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('front/global/vendor/select2/select2.css') }}">
    <link rel="stylesheet" href="{{ asset('front/global/vendor/bootstrap-datepicker/bootstrap-datepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('front/global/vendor/jt-timepicker/jquery-timepicker.css') }}">
{% endblock %}

{% block head_javascripts %}
    {{ parent() }}
    <link id="skinStyle" href="{{ asset('front/mmenu/assets/skins/teal.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block page %}
    <div class="page animsition">
        <div class="page-header padding-top-20 padding-bottom-10">
            <ol class="breadcrumb">
                <li>
                    <a href="{{ path('plot_show',{'id':action.cropCycle.plot.id}) }}">{{ action.cropCycle.plot.name }}</a>
                </li>
                <li><a href="{{ path('cropcycle_show',{'id':action.cropCycle.id}) }}">{{ action.cropCycle.name }}</a>
                </li>
                <li class="active">Editer une intervention</li>
            </ol>
        </div>
        <div class="page-content">
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3">
                    <div class="panel panel-bordered">
                        <div class="panel-heading">
                            <h3 class="panel-title">Editer l'intervention</h3>
                        </div>
                        <div class="panel-body">
                            {{ form_start(edit_form) }}
                            <div class="row">
                                <div class="col-lg-12">
                                    <h4 class="example-title">
                                        {{ form_label(edit_form.intervention) }}
                                    </h4>
                                    {{ form_widget(edit_form.intervention) }}
                                </div>
                            </div>
                            <div class="row margin-top-20 hidden">
                                <div class="col-lg-12">

                                    <h4 class="example-title">
                                        Date d'intervention <a href="#" style="text-transform: capitalize;
" id="add_period"><i class="icon md-plus-circle-o" aria-hidden="true"></i></a>
                                    </h4>
                                    {% form_theme edit_form 'AppBundle:form:datetime.html.twig' %}
                                    {{ form_widget(edit_form.periods) }}
                                </div>
                            </div>
                            <div class="row margin-top-20">
                                <div class="col-lg-12">
                                    <h4 class="example-title">
                                        {{ form_label(edit_form.tractors) }}
                                        <a href="{{ path('tractor_new') }}" style="text-transform: capitalize;
" id="add_period"><i class="icon md-plus-circle-o" aria-hidden="true"></i></a>
                                    </h4>
                                    {{ form_errors(edit_form.tractors) }}
                                    {{ form_widget(edit_form.tractors) }}
                                </div>
                                <div class="col-lg-12 margin-top-10">
                                    <h4 class="example-title">
                                        {{ form_label(edit_form.implements) }}
                                        <a href="{{ path('implement_new') }}" style="text-transform: capitalize;
" id="add_period"><i class="icon md-plus-circle-o" aria-hidden="true"></i></a>
                                    </h4>
                                    {{ form_errors(edit_form.implements) }}
                                    {{ form_widget(edit_form.implements) }}
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <a class="btn btn-default"
                               href="{{ path('cropcycle_show',{'id':action.cropCycle.id}) }}">Annuler</a>
                            <button class="btn btn-primary margin-left-10" type="submit">Enregistrer</button>
                            {{ form_end(edit_form) }}

                        </div>
                    </div>

                </div>
                <div class="col-lg-3">
                    <div class="panel panel-bordered">
                        <div class="panel-heading"><div class="panel-title">Actions sensibles</div></div>
                        <div class="panel-body">
                            {% if is_granted('DELETE', action) or is_granted('ROLE_ADMIN') %}
                                {{ form_start(delete_form) }}
                                <button class="btn btn-danger" type="submit">Supprimer</button>
                                {{ form_end(delete_form) }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block template_config %}
    {{ parent() }}
    <script src="{{ asset('front/global/vendor/select2/select2.min.js') }}"></script>
    <script src="{{ asset('front/global/js/components/select2.js') }}"></script>

    <script src="{{ asset('front/global/vendor/bootstrap-datepicker/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('front/global/vendor/bootstrap-datepicker/bootstrap-datepicker.fr.js') }}"></script>
    <script src="{{ asset('front/global/vendor/jt-timepicker/jquery.timepicker.js') }}"></script>
    <script src="{{ asset('front/global/vendor/datepair-js/datepair.min.js') }}"></script>
    <script src="{{ asset('front/global/vendor/datepair-js/jquery.datepair.min.js') }}"></script>

    <script src="{{ asset('front/global/js/components/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('front/global/js/components/jt-timepicker.js') }}"></script>
    <script src="{{ asset('front/global/js/components/datepair-js.js') }}"></script>
{% endblock %}


{% block javascripts %}
    {{ parent() }}

    <script type="text/javascript">
        $(document).ready(function () {
            var $container = $('div#action_edit_periods');
            var index = $container.find(':input').length;
            $('#add_period').click(function (e) {
                addPeriod($container);

                e.preventDefault(); // évite qu'un # apparaisse dans l'URL
                return false;
            });

            if (index == 0) {
                addPeriod($container);

            } else {
                $container.children('div').each(function () {
                    addDeleteLink($(this));
                });
            }

            function addPeriod($container) {
                var template = $container.attr('data-prototype')
                        .replace(/__name__label__/g, '')
                        .replace(/__name__/g, index)
                        .replace(/Start datetime/g, "Début d'intervention")
                        .replace(/End datetime/g, "Fin d'intervention")
                        .replace(/form-group/g, "form-group col-lg-12")
                        ;

                var $prototype = $(template);
                addDeleteLink($prototype);
                $container.append($prototype);


                $('input[id*="startDatetime_time"]').addClass("time start");
                $('input[id*="startDatetime_date"]').addClass("date start");
                $('input[id*="endDatetime_time"]').addClass("time end");
                $('input[id*="endDatetime_date"]').addClass("date end");

                // initialize input widgets first
                $('.time').timepicker({
                    'showDuration': true,
                    'timeFormat': 'G:i',
                    'show2400': true
                });

                $('.date').datepicker({
                    'format': 'dd/mm/yyyy',
                    'startView': 'months',
                    'minView': 'days',
                    'language': 'fr',
                    'autoclose': true
                });

                // initialize datepair
                var basicExampleEl = document.getElementById('action_edit_periods_' + (index));
                var datepair = new Datepair(basicExampleEl,{
                    anchor: 'null'
                });

                index++;
            }

            function addDeleteLink($prototype) {
                var $deleteLink = $('<a href="#" style="position: absolute;top: -5px;right: 20px;"><i class="btn btn-pure btn-danger icon waves-effect waves-circle waves-classicr md-close-circle-o" aria-hidden="true"></i></a>');
                $prototype.append($deleteLink);
                $deleteLink.click(function (e) {
                    $prototype.remove();

                    index--;

                    e.preventDefault();
                    return false;
                });
            }
        });
    </script>
{% endblock %}

src/AppBundle/Resources/views/action/index.html.twig
<table class="table table-hover">
    <tbody>
    {% for action in actions %}
        {% if is_granted('VIEW', action) or is_granted('ROLE_ADMIN') %}
            <tr>
                <td>
                    <div class="content">
                        <div class="title">
                            <a href="{{ path('action_show', { 'id': action.id }) }}">{{ action.name }}</a>
                        </div>
                        <div class="metas">
                            <span class="started">
                                <i class="icon md-calendar" aria-hidden="true"> </i>
                                {{ action.intervalLabel}}
                                {% if action.durationLabel != '' %}
                                <i class="icon md-time-interval margin-left-10" aria-hidden="true"></i>
                                {{ action.durationLabel }}
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </td>
                <td>
                    {% if action.status == "ActiveAction" %}
                        <span class="pull-right label label-danger  margin-right-10px">En cours</span>
                    {% elseif action.status == "CompletedAction" %}
                        <span class="pull-right label label-info  margin-right-10px">Terminé</span>
                    {% elseif action.status == "PotentialAction" %}
                        <span class="pull-right label label-default  margin-right-10px">A venir</span>
                    {% endif %}
                </td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

src/AppBundle/Resources/views/action/show.html.twig
{% extends 'base.html.twig' %}

{% block head_javascripts %}
    {{ parent() }}
    <link id="skinStyle" href="{{ asset('front/mmenu/assets/skins/teal.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block plugin_stylesheets %}
    {{ parent() }}
    <style>

        table.table-hover td:hover .appear {
            visibility: visible;
        }

        table.table-hover td .appear {
            visibility: hidden;
        }


    </style>
{% endblock %}

{% block page %}

    <div class="page animsition">
        <div class="page-header padding-top-20 padding-bottom-10">
            <ol class="breadcrumb">
                <li>
                    <a href="{{ path('plot_show',{'id':action.cropCycle.plot.id}) }}">{{ action.cropCycle.plot.name }}</a>
                </li>
                <li><a href="{{ path('cropcycle_show',{'id':action.cropCycle.id}) }}">{{ action.cropCycle.name }}</a>
                </li>
                <li class="active">{{ action.name }}</li>
            </ol>
        </div>
        <div class="page-content">
            <div class="row">
                <div class="col-lg-9">
                    <div class="panel panel-bordered">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ action.name }}</h3>
                            <div class="panel-actions">
                                {% if is_granted('EDIT', action) or is_granted('ROLE_ADMIN') %}
                                    <a class="btn btn-default btn-flat"
                                       href="{{ path('action_edit', { 'id': action.id }) }}">Editer</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="panel-body">
                            <h4 class="example-title">
                                Matériel utilisé
                            </h4>
                            {% if action.tractors is not empty and action.implements is not empty %}
                                <ul>
                                    {% for tractor in action.tractors %}
                                        <li>
                                            {{ tractor.name }}
                                        </li>
                                    {% endfor %}
                                    {% for implement in action.implements %}
                                        <li>
                                            {{ implement.name }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <p>
                                    Aucun matériel renseigné
                                </p>
                            {% endif %}

                            <h4 class="example-title margin-top-30">
                                Périodes d'intervention
                                <span class="label label-info">
                                    {{ action.progress['completed_actions'] }}
                                    / {{ action.progress['count_actions'] }}
                                </span>
                            </h4>
                            <table class="table table-hover">
                                <tbody>
                                {% for period in action.periods %}
                                    <tr>
                                        <td>{{ period.intervalLabel}}

                                            <a href="{{ path('event_edit',{'id':period.id}) }}">
                                                <i class="icon appear md-edit margin-left-10" style="color:darkgrey"
                                                   aria-hidden="true">
                                                </i>
                                            </a>
                                        </td>
                                        <td>
                                            <i class="icon md-time-interval" aria-hidden="true"></i>
                                            {{ period.durationLabel }}
                                        </td>
                                        <td>
                                            {% if period.status == "ActiveAction" %}
                                                <span class="pull-right label label-danger  margin-right-10px">En cours</span>
                                            {% elseif period.status == "CompletedAction" %}
                                                <span class="pull-right label label-info  margin-right-10px">Terminée</span>
                                            {% elseif period.status == "PotentialAction" %}
                                                <span class="pull-right label label-default  margin-right-10px">A venir</span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="panel">
                        <div class="panel-heading">
                            <div class="panel-title">
                                Actions sensibles
                            </div>
                        </div>
                        <div class="panel-body">


                            {% if is_granted('DELETE', action) or is_granted('ROLE_ADMIN') %}
                                {{ form_start(delete_form) }}
                                <button type="submit" class="btn btn-danger">Supprimer</button>
                                {{ form_end(delete_form) }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}